name: Feature Request
description: Suggest a new feature or enhancement for RdioCallsAPI
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        I'm trying to...
        Currently, RdioCallsAPI doesn't...
        This would be useful because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        The feature would...
        It could work by...
        Users would be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Another approach could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - No breaking changes
        - Minor breaking changes acceptable
        - Major breaking changes acceptable
        - Not sure
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how to implement this, please share
      placeholder: |
        This could be implemented by...
        The code might look like...

  - type: textarea
    id: examples
    attributes:
      label: Example Use Cases
      description: Provide examples of how this feature would be used
      render: python
      placeholder: |
        # Example configuration or code
        config:
          new_feature:
            enabled: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
        - label: I can provide testing/feedback during development
        - label: I have searched existing issues to ensure this hasn't been requested