name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --all-extras --dev
    
    - name: Check code formatting with black
      run: uv run black --check .
    
    - name: Check import sorting with isort
      run: uv run isort --check-only .
    
    - name: Lint with ruff
      run: uv run ruff check .
    
    - name: Type check with mypy
      run: uv run mypy src
    
    - name: Run tests with pytest
      run: uv run pytest -v --tb=short
    
    - name: Test CLI help
      run: uv run python cli.py --help
    
    - name: Test configuration generation
      run: uv run python cli.py init --output test-config.yaml